tomcat 설정 config 클래스 추가
**문제**
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986

-> get 방식 파라미터에 `[] 등 특수문자 넣을 시 발생하고 톰캣 400 페이지로 이동됨

**해결**
톰캣 서버 relaxedQueryChars 빈 설정으로 특수문자 허용